from enum import Enum


class CaseState(str, Enum):
    RECEIVED = "RECEIVED"
    AUTHENTICITY_REVIEW = "AUTHENTICITY_REVIEW"
    UNDERSTOOD = "UNDERSTOOD"
    ACTION_REQUIRED = "ACTION_REQUIRED"
    DOCUMENTS_REQUIRED = "DOCUMENTS_REQUIRED"
    READY_FOR_RESPONSE = "READY_FOR_RESPONSE"
    DRAFT_READY = "DRAFT_READY"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    CLARIFICATION_REQUIRED = "CLARIFICATION_REQUIRED"
    CLARIFICATION_IN_PROGRESS = "CLARIFICATION_IN_PROGRESS"
    RESOLVED = "RESOLVED"


class CaseEvent(str, Enum):
    """Events are the ONLY way state changes. The LLM cannot emit these; only
    deterministic code raises them, after validation."""
    NOTICE_INGESTED = "NOTICE_INGESTED"
    AUTHENTICITY_CLEARED = "AUTHENTICITY_CLEARED"
    EXPLAINED = "EXPLAINED"
    DOCUMENTS_MISSING = "DOCUMENTS_MISSING"
    DOCUMENTS_COMPLETE = "DOCUMENTS_COMPLETE"
    DRAFT_GENERATED = "DRAFT_GENERATED"
    SENT_FOR_APPROVAL = "SENT_FOR_APPROVAL"
    CITIZEN_APPROVED = "CITIZEN_APPROVED"
    DEPT_UNDER_REVIEW = "DEPT_UNDER_REVIEW"
    DEPT_RESOLVED = "DEPT_RESOLVED"
    DEPT_CLARIFICATION = "DEPT_CLARIFICATION"
    CITIZEN_STARTED_CLARIFICATION = "CITIZEN_STARTED_CLARIFICATION"
    CLARIFICATION_SUBMITTED = "CLARIFICATION_SUBMITTED"
